name: esr_dart_sdk
description: SDK for Utilizing European School Radio's Public API and its utilities.
version: 1.0.0
repository: https://github.com/European-School-Radio/ESR-Dart-SDK

environment:
  sdk: ">=3.10.4 <4.0.0"

# Add regular dependencies here.
dependencies:
  http: ^1.6.0
  intl: ^0.20.2
  html_unescape: ^2.0.0
  web_socket_channel: ^3.0.3
  jwt_decoder: ^2.0.1
  email_validator: ^3.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
