name: esr_dart_sdk
description: SDK for Utilizing European School Radio's Public API and its utilities.
version: 1.0.0
repository: https://github.com/European-School-Radio/ESR-Dart-SDK

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  http: ^1.2.2
  intl: ^0.19.0
  html_unescape: ^2.0.0
  web_socket_channel: ^3.0.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
